//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	Healthy HealthResponseStatus = "healthy"
)

// AppActionRequest defines model for AppActionRequest.
type AppActionRequest struct {
	AppSlug     string `json:"app_slug"`
	Environment string `json:"environment"`
}

// AppActionResponse defines model for AppActionResponse.
type AppActionResponse struct {
	Message *string `json:"message,omitempty"`
	Output  *string `json:"output,omitempty"`
	Status  *string `json:"status,omitempty"`
}

// CreateBinaryAppRequest defines model for CreateBinaryAppRequest.
type CreateBinaryAppRequest struct {
	AppSlug         string             `json:"app_slug"`
	Args            *[]string          `json:"args,omitempty"`
	ArtifactName    string             `json:"artifact_name"`
	ArtifactSource  string             `json:"artifact_source"`
	ArtifactVersion string             `json:"artifact_version"`
	CallbackUrl     *string            `json:"callback_url,omitempty"`
	DeploymentId    *string            `json:"deployment_id,omitempty"`
	Domain          *string            `json:"domain,omitempty"`
	EnvVars         *map[string]string `json:"env_vars,omitempty"`
	Environment     string             `json:"environment"`
	HealthcheckUrl  *string            `json:"healthcheck_url,omitempty"`
	Port            int                `json:"port"`
}

// CreateDockerAppRequest defines model for CreateDockerAppRequest.
type CreateDockerAppRequest struct {
	AppSlug         string             `json:"app_slug"`
	ArtifactSource  string             `json:"artifact_source"`
	ArtifactVersion string             `json:"artifact_version"`
	CallbackUrl     *string            `json:"callback_url,omitempty"`
	DeploymentId    *string            `json:"deployment_id,omitempty"`
	DockerCommand   *[]string          `json:"docker_command,omitempty"`
	Domain          *string            `json:"domain,omitempty"`
	EnvVars         *map[string]string `json:"env_vars,omitempty"`
	Environment     string             `json:"environment"`
	Port            int                `json:"port"`
	Ports           *[]string          `json:"ports,omitempty"`
	Volumes         *[]string          `json:"volumes,omitempty"`
}

// DeployBinaryAppRequest defines model for DeployBinaryAppRequest.
type DeployBinaryAppRequest struct {
	AppSlug         string    `json:"app_slug"`
	Args            *[]string `json:"args,omitempty"`
	ArtifactName    string    `json:"artifact_name"`
	ArtifactSource  string    `json:"artifact_source"`
	ArtifactVersion string    `json:"artifact_version"`
	CallbackUrl     *string   `json:"callback_url,omitempty"`
	DeploymentId    *string   `json:"deployment_id,omitempty"`
	Environment     string    `json:"environment"`
}

// DeployDockerAppRequest defines model for DeployDockerAppRequest.
type DeployDockerAppRequest struct {
	AppSlug         string  `json:"app_slug"`
	ArtifactSource  string  `json:"artifact_source"`
	ArtifactVersion string  `json:"artifact_version"`
	CallbackUrl     *string `json:"callback_url,omitempty"`
	DeploymentId    *string `json:"deployment_id,omitempty"`
	Environment     string  `json:"environment"`
}

// DeployResponse defines model for DeployResponse.
type DeployResponse struct {
	Logs    *string `json:"logs,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *string `json:"status,omitempty"`
}

// GenericObject defines model for GenericObject.
type GenericObject map[string]interface{}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  HealthResponseStatus `json:"status"`
	Version string               `json:"version"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// UpdateAgentRequest defines model for UpdateAgentRequest.
type UpdateAgentRequest struct {
	ArtifactVersion string `json:"artifact_version"`
}

// UpdateAgentResponse defines model for UpdateAgentResponse.
type UpdateAgentResponse struct {
	Message *string `json:"message,omitempty"`
	Status  *string `json:"status,omitempty"`
}

// UpdateAgentJSONRequestBody defines body for UpdateAgent for application/json ContentType.
type UpdateAgentJSONRequestBody = UpdateAgentRequest

// CreateBinaryAppJSONRequestBody defines body for CreateBinaryApp for application/json ContentType.
type CreateBinaryAppJSONRequestBody = CreateBinaryAppRequest

// CreateDockerAppJSONRequestBody defines body for CreateDockerApp for application/json ContentType.
type CreateDockerAppJSONRequestBody = CreateDockerAppRequest

// DeployBinaryAppJSONRequestBody defines body for DeployBinaryApp for application/json ContentType.
type DeployBinaryAppJSONRequestBody = DeployBinaryAppRequest

// DeployDockerAppJSONRequestBody defines body for DeployDockerApp for application/json ContentType.
type DeployDockerAppJSONRequestBody = DeployDockerAppRequest

// RestartAppJSONRequestBody defines body for RestartApp for application/json ContentType.
type RestartAppJSONRequestBody = AppActionRequest

// StartAppJSONRequestBody defines body for StartApp for application/json ContentType.
type StartAppJSONRequestBody = AppActionRequest

// StopAppJSONRequestBody defines body for StopApp for application/json ContentType.
type StopAppJSONRequestBody = AppActionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Update agent binary
	// (POST /agent/update)
	UpdateAgent(w http.ResponseWriter, r *http.Request)
	// Create binary app (install and start)
	// (POST /app/create/binary)
	CreateBinaryApp(w http.ResponseWriter, r *http.Request)
	// Create docker app (install and start)
	// (POST /app/create/docker)
	CreateDockerApp(w http.ResponseWriter, r *http.Request)
	// Deploy binary app (update and restart)
	// (POST /app/deploy/binary)
	DeployBinaryApp(w http.ResponseWriter, r *http.Request)
	// Deploy docker app (update and restart)
	// (POST /app/deploy/docker)
	DeployDockerApp(w http.ResponseWriter, r *http.Request)
	// Restart app service
	// (POST /app/restart)
	RestartApp(w http.ResponseWriter, r *http.Request)
	// Start app service
	// (POST /app/start)
	StartApp(w http.ResponseWriter, r *http.Request)
	// Stop app service
	// (POST /app/stop)
	StopApp(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Proxy selected Prometheus node metrics
	// (GET /metrics/node)
	GetNodeMetrics(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// UpdateAgent operation middleware
func (siw *ServerInterfaceWrapper) UpdateAgent(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAgent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBinaryApp operation middleware
func (siw *ServerInterfaceWrapper) CreateBinaryApp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBinaryApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDockerApp operation middleware
func (siw *ServerInterfaceWrapper) CreateDockerApp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDockerApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeployBinaryApp operation middleware
func (siw *ServerInterfaceWrapper) DeployBinaryApp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeployBinaryApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeployDockerApp operation middleware
func (siw *ServerInterfaceWrapper) DeployDockerApp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeployDockerApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestartApp operation middleware
func (siw *ServerInterfaceWrapper) RestartApp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestartApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartApp operation middleware
func (siw *ServerInterfaceWrapper) StartApp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopApp operation middleware
func (siw *ServerInterfaceWrapper) StopApp(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopApp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNodeMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetNodeMetrics(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNodeMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/agent/update", wrapper.UpdateAgent)
	m.HandleFunc("POST "+options.BaseURL+"/app/create/binary", wrapper.CreateBinaryApp)
	m.HandleFunc("POST "+options.BaseURL+"/app/create/docker", wrapper.CreateDockerApp)
	m.HandleFunc("POST "+options.BaseURL+"/app/deploy/binary", wrapper.DeployBinaryApp)
	m.HandleFunc("POST "+options.BaseURL+"/app/deploy/docker", wrapper.DeployDockerApp)
	m.HandleFunc("POST "+options.BaseURL+"/app/restart", wrapper.RestartApp)
	m.HandleFunc("POST "+options.BaseURL+"/app/start", wrapper.StartApp)
	m.HandleFunc("POST "+options.BaseURL+"/app/stop", wrapper.StopApp)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/metrics/node", wrapper.GetNodeMetrics)

	return m
}
